name: dotnet build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/dotnet

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: 9.0.102
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -warnaserror --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -r linux-arm64 -o ./bin/publish/linux-arm64 --no-restore --no-build
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-linux-arm64
        path: ./bin/publish/linux-arm64
