name: dotnet build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/dotnet

    steps:
    - uses: actions/checkout@v5.0.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v5.0.0
      with:
        dotnet-version: 9.0.305
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/dotnet
    - name: Build
      run: dotnet build -warnaserror --no-restore
      working-directory: ./src/dotnet
    - name: Test
      run: dotnet run --no-build --project ./src/dotnet/KeyVaultFuseTests/KeyVaultFuseTests.fsproj --summary
    - name: Publish arm64
      working-directory: ./src/dotnet/KeyVaultFuse
      run: dotnet publish -c Release -r linux-arm64 -o ./bin/publish/linux-arm64
    - name: Archive arm64
      uses: actions/upload-artifact@v4
      with:
        name: linux-arm64
        path: ./src/dotnet/KeyVaultFuse/bin/publish/linux-arm64
    - name: Publish x64
      working-directory: ./src/dotnet/KeyVaultFuse
      run: dotnet publish -c Release -r linux-x64 -o ./bin/publish/linux-x64
    - name: Archive x64
      uses: actions/upload-artifact@v4
      with:
        name: linux-x64
        path: ./src/dotnet/KeyVaultFuse/bin/publish/linux-x64
